// Code generated by "stringer -type=nexttype"; DO NOT EDIT.

package jpath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nIndexes-1]
	_ = x[nCondition-2]
	_ = x[nDepth-3]
	_ = x[nNextPath-0]
}

const _nexttype_name = "nNextPathnIndexesnConditionnDepth"

var _nexttype_index = [...]uint8{0, 9, 17, 27, 33}

func (i nexttype) String() string {
	if i < 0 || i >= nexttype(len(_nexttype_index)-1) {
		return "nexttype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nexttype_name[_nexttype_index[i]:_nexttype_index[i+1]]
}
