// Code generated by "stringer -type=nexttype"; DO NOT EDIT.

package jpath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nIndexes-1]
	_ = x[nCondition-2]
	_ = x[nDepth-3]
	_ = x[nNextPath-100]
	_ = x[nEnd-0]
}

const (
	_nexttype_name_0 = "nEndnIndexesnConditionnDepth"
	_nexttype_name_1 = "nNextPath"
)

var (
	_nexttype_index_0 = [...]uint8{0, 4, 12, 22, 28}
)

func (i nexttype) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _nexttype_name_0[_nexttype_index_0[i]:_nexttype_index_0[i+1]]
	case i == 100:
		return _nexttype_name_1
	default:
		return "nexttype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
